parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'
  - prettier
  - jest-dom
  - import

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:jest-dom/recommended
  - plugin:import/typescript
  - plugin:@next/next/recommended

env:
  es6: true
  browser: true
  jest: true
  node: true

settings:
  react:
    version: detect

rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/indent': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
  import/no-unresolved: off
  import/order:
    - error
    - newlines-between: always
      groups:
        - builtin
        - external
        - internal
        - [parent, sibling, index]
      alphabetize:
        order: 'asc'
      pathGroups:
        - pattern: '{@api/**,@templates,@organisms,@molecules,@providers,@logic/**,@tests/**,@msw,@theme}'
          group: internal
          position: before
      pathGroupsExcludedImportTypes:
        - builtin
  no-console:
    - error
    - allow: [warn, error]
  prettier/prettier:
    - error
    - endOfLine: auto
  react/react-in-jsx-scope: off
  react/display-name: off
  react/prop-types: off
